name: app_portaria
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  validatorless: ^1.2.3
  shared_preferences: ^2.0.15
  local_auth: ^2.1.6
  flutter_platform_alert: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.5
  mask_text_input_formatter: ^2.4.0
  crypto: ^3.0.3
  http: ^0.13.6
  onesignal_flutter: ^3.5.1
  intl:
  shimmer: ^3.0.0
  whatsapp_unilink: ^2.1.0
  reorderable_grid_view: ^2.2.6
  flutter_draggable_gridview: ^0.0.8
  badges: ^3.1.1
  flutter_html: ^3.0.0-alpha.3
  diacritic: ^0.1.4
  email_validator: ^2.1.17
  cached_network_image: ^3.2.3
  date_time_picker: ^2.1.0
  
  
flutter_icons:
  image_path: "assets/logo_azul.png"
  ios: true
  remove_alpha_ios: true
  android: "launch_icon"
  adaptive_icon_foreground: "assets/logo_azul.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations: # Add this line
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/